version: '3'

services:
  web:
    image: nginx:alpine
    depends_on:
      - backend
      - postgres
    ports:
      - "8000:80"
    networks:
      - custom
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
      bash -c "wait-for-it --service postgres:5432 -t 0
      && alembic upgrade head 
      && python3.8 main.py --server seed
      && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    networks:
      - custom
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1
    ports: 
      - "127.0.0.1:5432:5432"
    restart: always
    networks:
      - custom
    environment:
      - POSTGRES_USER=courier
      - POSTGRES_PASSWORD=courier
      - POSTGRES_DB=courier

  
networks:
  custom: