"""empty message

Revision ID: f6e1635857f4
Revises: 
Create Date: 2023-11-09 16:49:18.203853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e1635857f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('districts', sa.ARRAY(sa.String(length=20)), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_couriers_districts'), 'couriers', ['districts'], unique=False)
    op.create_index(op.f('ix_couriers_id'), 'couriers', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('districts', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('works', 'complited', name='status'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('execution_time', sa.Time(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_courier_id'), 'orders', ['courier_id'], unique=False)
    op.create_index(op.f('ix_orders_execution_time'), 'orders', ['execution_time'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_execution_time'), table_name='orders')
    op.drop_index(op.f('ix_orders_courier_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_couriers_id'), table_name='couriers')
    op.drop_index(op.f('ix_couriers_districts'), table_name='couriers')
    op.drop_table('couriers')
    # ### end Alembic commands ###
